=== kskaiser/KBTA-Viewer/data/TAK.V5.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XML Spy v4.1 U (http://www.xmlspy.com) by Denis (Ben-Gurion University) -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:element name="Knowledge-Base">
		<xs:annotation>
			<xs:documentation>Comment describing your root element</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence maxOccurs="unbounded">
				<xs:element ref="RawNumericConcept" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element ref="RawNominalConcept" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element ref="RawOrdinalConcept" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element ref="ValueAbstractionConcept" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element ref="LogicAbstractionConcept" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element ref="ContextConcept" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element ref="PatternConcept" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
			<xs:attribute name="id" type="xs:string" use="optional"/>
			<xs:attribute name="name" type="xs:string" use="optional"/>
		</xs:complexType>
	</xs:element>
	<xs:complexType name="Concept">
		<xs:sequence>
			<xs:element name="LocalPersistence">
				<xs:complexType>
					<xs:attribute name="goodBefore" type="xs:int" use="required"/>
					<xs:attribute name="goodAfter" type="xs:int" use="required"/>
					<xs:attribute name="timeUnit" type="xs:string" use="required"/>
				</xs:complexType>
			</xs:element>
			<xs:element name="TemporalSemanticProperties">
				<xs:complexType>
					<xs:attribute name="concenatable" type="xs:boolean"/>
					<xs:attribute name="downwardHereditary" type="xs:boolean"/>
					<xs:attribute name="upwardHereditary" type="xs:boolean"/>
					<xs:attribute name="forward" type="xs:boolean"/>
					<xs:attribute name="backward" type="xs:boolean"/>
					<xs:attribute name="solid" type="xs:boolean"/>
					<xs:attribute name="gestalt" type="xs:boolean"/>
				</xs:complexType>
			</xs:element>
			<xs:element name="Synonyms" minOccurs="0">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="Synonym" minOccurs="0" maxOccurs="unbounded">
							<xs:complexType>
								<xs:attribute name="name" type="xs:string"/>
							</xs:complexType>
						</xs:element>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
			<xs:element name="StandardTerms" minOccurs="0">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="StandardTerm" minOccurs="0" maxOccurs="unbounded">
							<xs:complexType>
								<xs:attribute name="vocabulary" type="xs:string" use="required"/>
								<xs:attribute name="key" type="xs:string" use="required"/>
								<xs:attribute name="CUI" type="xs:string" use="optional"/>
							</xs:complexType>
						</xs:element>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
		<xs:attribute name="id" type="xs:string" use="required"/>
		<xs:attribute name="name" type="xs:string" use="required"/>
		<xs:attribute name="description" type="xs:string" use="optional"/>
		<xs:attribute name="semi_formal" type="xs:string" use="optional"/>
		<xs:attribute name="type" type="xs:string" use="required"/>
	</xs:complexType>
	<xs:element name="RawNumericConcept">
		<xs:complexType>
			<xs:complexContent>
				<xs:extension base="Concept">
					<xs:sequence>
						<xs:element name="NumericAllowedValues">
							<xs:complexType>
								<xs:attribute name="Scale" type="xs:string" use="optional" default="ratio"/>
								<xs:attribute name="Units" type="xs:string" use="required"/>
								<xs:attribute name="MinValue" type="xs:double" use="required"/>
								<xs:attribute name="MaxValue" type="xs:double" use="required"/>
							</xs:complexType>
						</xs:element>
					</xs:sequence>
				</xs:extension>
			</xs:complexContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="RawNominalConcept">
		<xs:complexType>
			<xs:complexContent>
				<xs:extension base="Concept">
					<xs:sequence>
						<xs:element name="NominalAllowedValues">
							<xs:complexType>
								<xs:sequence>
									<xs:element name="NominalStringValue" maxOccurs="unbounded">
										<xs:complexType>
											<xs:attribute name="value" type="xs:string" use="required"/>
										</xs:complexType>
									</xs:element>
								</xs:sequence>
							</xs:complexType>
						</xs:element>
					</xs:sequence>
				</xs:extension>
			</xs:complexContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="RawOrdinalConcept">
		<xs:complexType>
			<xs:complexContent>
				<xs:extension base="Concept">
					<xs:sequence>
						<xs:element name="OrdinalAllowedValues">
							<xs:complexType>
								<xs:sequence>
									<xs:element name="OrdinalStringValue" maxOccurs="unbounded">
										<xs:complexType>
											<xs:attribute name="order" type="xs:int" use="required"/>
											<xs:attribute name="value" type="xs:string" use="required"/>
										</xs:complexType>
									</xs:element>
								</xs:sequence>
							</xs:complexType>
						</xs:element>
					</xs:sequence>
				</xs:extension>
			</xs:complexContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="ValueAbstractionConcept">
		<xs:complexType>
			<xs:complexContent>
				<xs:extension base="Concept">
					<xs:sequence>
						<xs:element ref="NecessaryContext"/>
						<xs:element ref="DerivedFrom"/>
						<xs:element ref="DerivedFromComponents"/>
					</xs:sequence>
				</xs:extension>
			</xs:complexContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="LogicAbstractionConcept">
		<xs:complexType>
			<xs:complexContent>
				<xs:extension base="Concept">
					<xs:sequence>
						<xs:element ref="NecessaryContext"/>
						<xs:element ref="DerivedFrom"/>
					</xs:sequence>
					<xs:attribute name="ComponentsRelation" use="required"/>
					<xs:attribute name="K"/>
				</xs:extension>
			</xs:complexContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="ContextConcept">
		<xs:complexType>
			<xs:complexContent>
				<xs:extension base="Concept">
					<xs:sequence>
						<xs:element ref="DerivedFrom"/>
						<xs:element name="GeneratedFrom" type="GeneratedBy"/>
						<xs:element name="GeneratedUntil" type="GeneratedBy"/>
					</xs:sequence>
				</xs:extension>
			</xs:complexContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="PatternConcept">
		<xs:complexType>
			<xs:complexContent>
				<xs:extension base="Concept">
					<xs:sequence>
						<xs:element ref="NecessaryContext"/>
						<xs:element ref="DerivedFrom"/>
						<xs:element name="PatternComponents">
							<xs:complexType>
								<xs:sequence>
									<xs:element name="PatternComponent" maxOccurs="unbounded">
										<xs:complexType>
											<xs:sequence>
												<xs:element name="ConceptID_Name" type="ConceptID_Name"/>
												<xs:element name="componentLocalConstraints">
													<xs:complexType>
														<xs:sequence>
															<xs:element ref="componentValueConstraints"/>
															<xs:element name="componentTimeConstraints">
																<xs:complexType>
																	<xs:sequence>
																		<xs:element name="ReferencePoint" type="ConceptID_Name"/>
																	</xs:sequence>
																	<xs:attribute name="StartPoint" type="xs:dateTime"/>
																	<xs:attribute name="EarliestStartPoint" type="xs:dateTime"/>
																	<xs:attribute name="LatestStartPoint" type="xs:dateTime"/>
																	<xs:attribute name="EndPoint" type="xs:dateTime"/>
																	<xs:attribute name="EarliestEndPoint" type="xs:dateTime"/>
																	<xs:attribute name="LatestEndPoint" type="xs:dateTime"/>
																	<xs:attribute name="referencePositionNumber"/>
																	<xs:attribute name="referenceBoundaryPoint"/>
																	<xs:attribute name="timeUnit"/>
																	<xs:attribute name="relativeStartPoint"/>
																	<xs:attribute name="relativeEarliestStartPoint"/>
																	<xs:attribute name="relativeLatestStartPoint"/>
																	<xs:attribute name="relativeEndPoint"/>
																	<xs:attribute name="relativeEarliestEndPoint"/>
																	<xs:attribute name="relativeLatestEndPoint"/>
																	<xs:attribute name="MinDuration"/>
																	<xs:attribute name="MaxDuration"/>
																</xs:complexType>
															</xs:element>
														</xs:sequence>
													</xs:complexType>
												</xs:element>
											</xs:sequence>
											<xs:attribute name="alias" type="xs:string"/>
										</xs:complexType>
									</xs:element>
								</xs:sequence>
							</xs:complexType>
						</xs:element>
						<xs:element name="PatternTemporalPairwiseConstraints">
							<xs:complexType>
								<xs:sequence>
									<xs:element name="TemporalPairwiseConstraint" minOccurs="0" maxOccurs="unbounded">
										<xs:complexType>
											<xs:attribute name="componentAliasA"/>
											<xs:attribute name="componentAliasB"/>
											<xs:attribute name="boundaryPointA"/>
											<xs:attribute name="boundaryPointB"/>
											<xs:attribute name="Operator"/>
											<xs:attribute name="timeUnit"/>
											<xs:attribute name="minDifference"/>
											<xs:attribute name="maxDifference"/>
										</xs:complexType>
									</xs:element>
								</xs:sequence>
							</xs:complexType>
						</xs:element>
						<xs:element name="PatternPeriodicConstraints">
							<xs:complexType>
								<xs:attribute name="timeUnit"/>
								<xs:attribute name="minGap"/>
								<xs:attribute name="maxGap"/>
								<xs:attribute name="Operator"/>
								<xs:attribute name="minCardinalityValue"/>
								<xs:attribute name="maxCardinalityValue"/>
								<xs:attribute name="cardinalityValue"/>
								<xs:attribute name="minEnvelope"/>
								<xs:attribute name="maxEnvelope"/>
							</xs:complexType>
						</xs:element>
					</xs:sequence>
					<xs:attribute name="patternComponentsRelation"/>
					<xs:attribute name="K"/>
				</xs:extension>
			</xs:complexContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="NecessaryContext">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="ConceptID_Name" type="ConceptID_Name" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="DerivedFrom">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="ConceptID_Name" type="ConceptID_Name" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="DerivedFromComponents">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="DerivedFromComponent">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="ConceptID_Name" type="ConceptID_Name"/>
							<xs:element ref="componentValueConstraints"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="componentValueConstraints">
		<xs:complexType>
			<xs:attribute name="minValue"/>
			<xs:attribute name="maxValue"/>
			<xs:attribute name="value"/>
			<xs:attribute name="Operator"/>
		</xs:complexType>
	</xs:element>
	<xs:complexType name="ConceptID_Name">
		<xs:attribute name="ConceptID" use="required"/>
		<xs:attribute name="ConceptName"/>
	</xs:complexType>
	<xs:complexType name="GeneratedBy">
		<xs:sequence>
			<xs:element name="ConceptID_Name" type="ConceptID_Name"/>
			<xs:element ref="componentValueConstraints"/>
		</xs:sequence>
		<xs:attribute name="timeUnit"/>
		<xs:attribute name="timeGap"/>
		<xs:attribute name="boundaryPoint"/>
	</xs:complexType>
</xs:schema>

=== kskaiser/KBTA-Viewer/data/GDM_GoldStandard_kbta.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Knowledge-Base xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="TAK.V5.xsd">

    <RawNominalConcept id="99993" name="GDM [raw]"
        description="GDM" type="RawNominal">
        <LocalPersistence goodBefore="0" goodAfter="0" timeUnit="Seconds"/>
        <TemporalSemanticProperties concenatable="false" downwardHereditary="false"
            upwardHereditary="false" forward="false" backward="false" solid="false" gestalt="false"/>
        <Synonyms/>
        <StandardTerms>
            <StandardTerm vocabulary="UMLS" key="Gestional Diabetes" CUI="C0085207"/>
        </StandardTerms>
        <NominalAllowedValues>
            <NominalStringValue value="true"/>
            <NominalStringValue value="false"/>
        </NominalAllowedValues>
    </RawNominalConcept>
    
    <ValueAbstractionConcept id="99992" name="GDM"
        description="GDM" type="ValueAbstraction">
        <LocalPersistence goodBefore="0" goodAfter="0" timeUnit="Seconds"/>
        <TemporalSemanticProperties concenatable="false" downwardHereditary="false"
            upwardHereditary="false" forward="false" backward="false" solid="false" gestalt="false"/>
        <Synonyms/>
        <StandardTerms/>
        <NecessaryContext/>
        <DerivedFrom>
            <ConceptID_Name ConceptID="99993" ConceptName="GDM [raw]"/>
        </DerivedFrom>
        <DerivedFromComponents>
            <DerivedFromComponent>
                <ConceptID_Name ConceptID="99993" ConceptName="GDM [raw]"/>
                <componentValueConstraints value="true" Operator="Equals"/>
            </DerivedFromComponent>
        </DerivedFromComponents>
    </ValueAbstractionConcept>
    
    

    <ValueAbstractionConcept id="99999" name="Women with GDM" description="Women with GDM"
        type="ValueAbstraction">
        <LocalPersistence goodBefore="0" goodAfter="0" timeUnit="Seconds"/>
        <TemporalSemanticProperties concenatable="false" downwardHereditary="false"
            upwardHereditary="false" forward="false" backward="false" solid="false" gestalt="false"/>
        <Synonyms/>
        <StandardTerms/>
        <NecessaryContext/>
        <DerivedFrom>
            <ConceptID_Name ConceptID="100000" ConceptName="Woman with GDM [Logic]"/>
        </DerivedFrom>
        <DerivedFromComponents>
            <DerivedFromComponent>
                <ConceptID_Name ConceptID="100000" ConceptName="Woman with GDM [Logic]"/>
                <componentValueConstraints value="true" Operator="Equals"/>
            </DerivedFromComponent>
        </DerivedFromComponents>
    </ValueAbstractionConcept>


    <LogicAbstractionConcept ComponentsRelation="AND" K="0" id="100000"
        name="Woman with GDM [Logic]" description="Woman with GDM [Logic]" type="LogicAbstraction">
        <LocalPersistence goodBefore="0" goodAfter="0" timeUnit="Seconds"/>
        <TemporalSemanticProperties concenatable="false" downwardHereditary="false"
            upwardHereditary="false" forward="false" backward="false" solid="false" gestalt="false"/>
        <Synonyms/>
        <StandardTerms/>
        <NecessaryContext/>
        <DerivedFrom>
            <ConceptID_Name ConceptID="100002"/>
            <!-- woman -->
            <ConceptID_Name ConceptID="99992"/>
            <!-- GDM -->
        </DerivedFrom>
    </LogicAbstractionConcept>


    <RawNominalConcept id="100001" name="sex" description="sex" type="RawNominal">
        <LocalPersistence goodBefore="0" goodAfter="0" timeUnit="Seconds"/>
        <TemporalSemanticProperties concenatable="false" downwardHereditary="false"
            upwardHereditary="false" forward="false" backward="false" solid="false" gestalt="false"/>
        <Synonyms/>
        <StandardTerms>
            <StandardTerm vocabulary="UMLS" key="sex" CUI="C1522384"/>
        </StandardTerms>
        <NominalAllowedValues>
            <NominalStringValue value="female"/>
            <NominalStringValue value="male"/>
        </NominalAllowedValues>
    </RawNominalConcept>

    <ValueAbstractionConcept id="100002" name="woman" description="woman" type="ValueAbstraction">
        <LocalPersistence goodBefore="0" goodAfter="0" timeUnit="Seconds"/>
        <TemporalSemanticProperties concenatable="false" downwardHereditary="false"
            upwardHereditary="false" forward="false" backward="false" solid="false" gestalt="false"/>
        <StandardTerms>
            <StandardTerm vocabulary="UMLS" key="woman" CUI="C0043210"/>
        </StandardTerms>
        <NecessaryContext/>
        <DerivedFrom>
            <ConceptID_Name ConceptID="100001" ConceptName="sex"/>
        </DerivedFrom>
        <DerivedFromComponents>
            <DerivedFromComponent>
                <ConceptID_Name ConceptID="100001" ConceptName="sex"/>
                <componentValueConstraints value="female" Operator="Equals"/>
            </DerivedFromComponent>
        </DerivedFromComponents>
    </ValueAbstractionConcept>


    <RawNominalConcept id="100004" name="pregnancy" description="pregnancy" type="RawNominal">
        <LocalPersistence goodBefore="0" goodAfter="0" timeUnit="Seconds"/>
        <TemporalSemanticProperties concenatable="false" downwardHereditary="false"
            upwardHereditary="false" forward="false" backward="false" solid="false" gestalt="false"/>
        <Synonyms/>
        <StandardTerms>
            <StandardTerm vocabulary="UMLS" key="pregnancy" CUI="C0032961"/>
        </StandardTerms>
        <NominalAllowedValues>
            <NominalStringValue value="true"/>
            <NominalStringValue value="false"/>
        </NominalAllowedValues>
    </RawNominalConcept>

    <!-- all pregnant woman -->

    <ContextConcept id="100005" name="pregnant woman" description="pregnant woman" type="Context">
        <LocalPersistence goodBefore="0" goodAfter="0" timeUnit="Seconds"/>
        <TemporalSemanticProperties concenatable="false" downwardHereditary="false"
            upwardHereditary="false" forward="false" backward="false" solid="false" gestalt="false"/>
        <Synonyms/>
        <StandardTerms/>
        <DerivedFrom>
            <ConceptID_Name ConceptID="100002" ConceptName="woman"/>
        </DerivedFrom>
        <GeneratedFrom timeUnit="Seconds" timeGap="0" boundaryPoint="Start">
            <ConceptID_Name ConceptID="100004" ConceptName="pregnancy"/>
            <componentValueConstraints value="true" Operator="Equals"/>
        </GeneratedFrom>
        <GeneratedUntil timeUnit="Seconds" timeGap="0" boundaryPoint="End">
            <ConceptID_Name ConceptID="100004" ConceptName="pregnancy"/>
            <componentValueConstraints value="true" Operator="Equals"/>
        </GeneratedUntil>
    </ContextConcept>



    <!-- for women at high risk for GDM who are unable to take an oral glucose load-->
    <!-- high risk for GDM true/false-->
    <RawNominalConcept id="100007" name="high risk for GDM" description="high risk for GDM"
        type="RawNominal">
        <LocalPersistence goodBefore="0" goodAfter="0" timeUnit="Seconds"/>
        <TemporalSemanticProperties concenatable="false" downwardHereditary="false"
            upwardHereditary="false" forward="false" backward="false" solid="false" gestalt="false"/>
        <Synonyms/>
        <StandardTerms>
            <StandardTerm vocabulary="UMLS" key="?" CUI="?"/>
        </StandardTerms>
        <NominalAllowedValues>
            <NominalStringValue value="true"/>
            <NominalStringValue value="false"/>
        </NominalAllowedValues>
    </RawNominalConcept>

    <ValueAbstractionConcept id="100008" name="woman with high risk for GDM"
        description="woman with high risk for GDM" type="ValueAbstraction">
        <LocalPersistence goodBefore="0" goodAfter="0" timeUnit="Seconds"/>
        <TemporalSemanticProperties concenatable="false" downwardHereditary="false"
            upwardHereditary="false" forward="false" backward="false" solid="false" gestalt="false"/>
        <StandardTerms>
            <StandardTerm vocabulary="UMLS" key="woman with high risk for GDM" CUI="?"/>
        </StandardTerms>
        <NecessaryContext/>
        <DerivedFrom>
            <ConceptID_Name ConceptID="99998" ConceptName="woman with high risk for GDM [Logic]"/>
        </DerivedFrom>
        <DerivedFromComponents>
            <DerivedFromComponent>
                <ConceptID_Name ConceptID="99998" ConceptName="woman with high risk for GDM [Logic]"/>
                <componentValueConstraints value="true" Operator="Equals"/>
            </DerivedFromComponent>
        </DerivedFromComponents>
    </ValueAbstractionConcept>

    <LogicAbstractionConcept ComponentsRelation="AND" K="0" id="99998"
        name="woman with high risk for GDM [Logic]"
        description="woman with high risk for GDM [Logic]" type="LogicAbstraction">
        <LocalPersistence goodBefore="0" goodAfter="0" timeUnit="Seconds"/>
        <TemporalSemanticProperties concenatable="false" downwardHereditary="false"
            upwardHereditary="false" forward="false" backward="false" solid="false" gestalt="false"/>
        <Synonyms/>
        <StandardTerms/>
        <NecessaryContext/>
        <DerivedFrom>
            <ConceptID_Name ConceptID="100007"/>
            <!-- high risk for GDM -->
            <ConceptID_Name ConceptID="100002"/>
            <!-- woman -->
        </DerivedFrom>
    </LogicAbstractionConcept>



    <RawNominalConcept id="100009" name="unable to take an oral glucose load"
        description="unable to take an oral glucose load" type="RawNominal">
        <LocalPersistence goodBefore="0" goodAfter="0" timeUnit="Seconds"/>
        <TemporalSemanticProperties concenatable="false" downwardHereditary="false"
            upwardHereditary="false" forward="false" backward="false" solid="false" gestalt="false"/>
        <Synonyms/>
        <StandardTerms>
            <StandardTerm vocabulary="UMLS" key="?" CUI="?"/>
